# Generated by Django 5.2.1 on 2026-06-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('API', 'API'), ('DOMAIN', 'DOMAIN'), ('SERVER', 'SERVER'), ('CONTAINER', 'CONTAINER'), ('REPOSITORY', 'REPOSITORY')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('criticality', models.CharField(default='MEDIUM', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
        ),
    ]
