# Generated by Django 5.2.1 on 2026-06-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('ACCEPTED', 'ACCEPTED')], default='OPEN', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scanjob')),
            ],
        ),
    ]
