# Generated by Django 5.2.1 on 2026-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scanjob_created_at_scanjob_log_scanjob_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='output_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='name',
            field=models.CharField(default='Scan Job', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='tool',
            field=models.CharField(choices=[('GITLEAKS', 'Gitleaks'), ('SEMGREP', 'Semgrep'), ('TRIVY', 'Trivy'), ('DEPENDENCY_CHECK', 'Dependency Check')], max_length=50),
        ),
    ]
