# Generated by Django 5.2.1 on 2026-06-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
        migrations.AddField(
            model_name='repository',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project'),
        ),
    ]
