# Generated by Django 5.2.1 on 2026-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_rename_active_repository_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='branch',
            new_name='default_branch',
        ),
        migrations.AlterField(
            model_name='repository',
            name='git_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
